const Content = () => {
  return (
    <div className="md:w-1/2 mx-auto py-16 px-6">
      <h2 className="text-center text-4xl font-semibold mb-4">
        Terms & Conditions
      </h2>
      <p className="text-center text-gray-600 text-sm">
        Effective Date: 1 March 2025
      </p>
      <div className="mt-8 text-gray-800">
        <p>
          Welcome to Corena AI. By accessing or using our platform, you agree to
          comply with and be bound by these Terms & Conditions. If you do not
          agree, please do not use our services.
        </p>
        <br />
        <div className="space-y-4 mb-4">
          <p>
            This document is an electronic record in terms of Information
            Technology Act, 2000 and rules there under as applicable and the
            amended provisions pertaining to electronic records in various
            statutes as amended by the Information Technology Act, 2000. This
            electronic record is generated by a computer system and does not
            require any physical or digital signatures.
          </p>

          <p>
            This document is published in accordance with the provisions of Rule
            3 (1) of the Information Technology (Intermediaries guidelines)
            Rules, 2011 that require publishing the rules and regulations,
            privacy policy and Terms of Use for access or usage of domain name
            corena.mapsily.com ('Website'), including the related mobile site
            and mobile application (hereinafter referred to as 'Platform').
          </p>

          <p>
            The Platform is owned by WELLMINTO HOME SERVICES PRIVATE LIMITED, a
            company incorporated under the Companies Act, 1956 with its
            registered office at 1276, Preet Vihar, Roorkee, Roorkee, India
            (hereinafter referred to as "Platform Owner", 'we', 'us', 'our').
          </p>

          <p>
            Your use of the Platform and services and tools are governed by the
            following terms and conditions ("Terms of Use") as applicable to the
            Platform including the applicable policies which are incorporated
            herein by way of reference. If You transact on the Platform, You
            shall be subject to the policies that are applicable to the Platform
            for such transaction.
          </p>

          <p>
            For the purpose of these Terms of Use, wherever the context so
            requires "you", 'your' or "user" shall mean any natural or legal
            person who has agreed to become a user/buyer on the Platform.
          </p>

          <h3 className="text-xl font-semibold">Key Terms</h3>
          <ul className="list-disc pl-6 space-y-2">
            <li>
              To access and use the Services, you agree to provide true,
              accurate and complete information to us during and after
              registration, and you shall be responsible for all acts done
              through the use of your registered account on the Platform.
            </li>

            <li>
              Neither we nor any third parties provide any warranty or guarantee
              as to the accuracy, timeliness, performance, completeness or
              suitability of the information and materials offered on this
              website or through the Services.
            </li>

            <li>
              Your use of our Services and the Platform is solely and entirely
              at your own risk and discretion for which we shall not be liable
              to you in any manner.
            </li>

            <li>
              The contents of the Platform and the Services are proprietary to
              us and are licensed to us.
            </li>

            <li>
              You agree to pay us the charges associated with availing the
              Services.
            </li>

            <li>
              You agree not to use the Platform and/or Services for any purpose
              that is unlawful, illegal or forbidden by these Terms.
            </li>
          </ul>

          <h3 className="text-xl font-semibold">Jurisdiction</h3>
          <p>
            These Terms and any dispute or claim relating to it, or its
            enforceability, shall be governed by and construed in accordance
            with the laws of India.
          </p>

          <p>
            All disputes arising out of or in connection with these Terms shall
            be subject to the exclusive jurisdiction of the courts in Roorkee
            and Uttarakhand.
          </p>
        </div>
        <span>
          For questions regarding these terms, contact us at contact@mapsily.com
        </span>
      </div>
    </div>
  );
};

export default Content;
